using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Runtime.Serialization;
using System.Threading;

namespace CrownPeak.AccessAPI
{
	[DataContract(Name="FilterExpression", Namespace="http://schemas.datacontract.org/2004/07/CrownPeakApp.Filters")]
	[DebuggerStepThrough]
	[GeneratedCode("System.Runtime.Serialization", "4.0.0.0")]
	[KnownType(typeof(ActionData))]
	[KnownType(typeof(ActionType))]
	[KnownType(typeof(ActiveStandardsCheckpoint))]
	[KnownType(typeof(ActiveStandardsData))]
	[KnownType(typeof(ActiveStandardsHighlight))]
	[KnownType(typeof(ActiveStandardsStatus))]
	[KnownType(typeof(ActivityUserData))]
	[KnownType(typeof(AddConnectorRequest))]
	[KnownType(typeof(AddConnectorResponse))]
	[KnownType(typeof(AddPackageConfigDataRequest))]
	[KnownType(typeof(AddPackageConfigDataResponse))]
	[KnownType(typeof(AdvancedSearchRequest))]
	[KnownType(typeof(AdvancedSearchResponse))]
	[KnownType(typeof(AlertActionType))]
	[KnownType(typeof(ApprovedHostname))]
	[KnownType(typeof(AssetChangeset))]
	[KnownType(typeof(AssetObjectType))]
	[KnownType(typeof(AssetPropertyNames))]
	[KnownType(typeof(AssetPublishAuditData))]
	[KnownType(typeof(AssetRefreshReportData))]
	[KnownType(typeof(AssetRenderPerformanceData))]
	[KnownType(typeof(AssetRenderPerformanceHistory))]
	[KnownType(typeof(AssetRenderPerformanceHistoryItem))]
	[KnownType(typeof(AssetRenderPerformanceSummary))]
	[KnownType(typeof(AssetReportResponse))]
	[KnownType(typeof(AssetResult))]
	[KnownType(typeof(AssetsField))]
	[KnownType(typeof(AssetsMeta))]
	[KnownType(typeof(AssetStatus))]
	[KnownType(typeof(AssetType))]
	[KnownType(typeof(AssetWCOChangeset))]
	[KnownType(typeof(AssetWorkflowSchedule))]
	[KnownType(typeof(AttachmentPublishPath))]
	[KnownType(typeof(AuditData))]
	[KnownType(typeof(AuthenticateResponseWCF))]
	[KnownType(typeof(BaseRequest))]
	[KnownType(typeof(BehavioralRule))]
	[KnownType(typeof(BehavioralRuleType))]
	[KnownType(typeof(CallEntity))]
	[KnownType(typeof(CallEntitySysInfo))]
	[KnownType(typeof(CancelUploadRequest))]
	[KnownType(typeof(CancelUploadResponse))]
	[KnownType(typeof(CancelUploadsRequest))]
	[KnownType(typeof(CancelUploadsResponse))]
	[KnownType(typeof(ClearCacheLinkResponse))]
	[KnownType(typeof(ClearErrorsResponse))]
	[KnownType(typeof(ClearQueuedAssetsResponse))]
	[KnownType(typeof(CloneAssetRequest))]
	[KnownType(typeof(CloneAssetResponse))]
	[KnownType(typeof(CloneCustomCSharpAssetRequest))]
	[KnownType(typeof(CloneCustomCSharpAssetResponse))]
	[KnownType(typeof(CloneGroupResponse))]
	[KnownType(typeof(ClonePublishingPackageRequest))]
	[KnownType(typeof(ClonePublishingPackageResponse))]
	[KnownType(typeof(CloneWorkflowResponse))]
	[KnownType(typeof(CrownPeak.AccessAPI.Comparison))]
	[KnownType(typeof(ConfirmEmailSenderRequest))]
	[KnownType(typeof(ConfirmEmailSenderResponse))]
	[KnownType(typeof(ConnectorAsset))]
	[KnownType(typeof(ConnectorConfigData))]
	[KnownType(typeof(ConnectorSelectorData))]
	[KnownType(typeof(CopyAssetRequest))]
	[KnownType(typeof(CopyAssetResponse))]
	[KnownType(typeof(CopyAssetsRequest))]
	[KnownType(typeof(CopyAssetsResponse))]
	[KnownType(typeof(CountStatSummary))]
	[KnownType(typeof(CountType))]
	[KnownType(typeof(cpAclType))]
	[KnownType(typeof(cpActivityUser))]
	[KnownType(typeof(cpAssetRenderType))]
	[KnownType(typeof(CpCompilerError))]
	[KnownType(typeof(cpConstPackageStateType))]
	[KnownType(typeof(cpDiagnosticsErrorerrorCodes))]
	[KnownType(typeof(cpKVPOfintstring))]
	[KnownType(typeof(cpKVPOfSearchFieldTypeArrayOfComparisonv_SQRvoIg))]
	[KnownType(typeof(cpListscpKeyValuePair))]
	[KnownType(typeof(cpPublishPublishingActivityDetailRequest))]
	[KnownType(typeof(cpPublishPublishingActivityDetailRequestType))]
	[KnownType(typeof(cpPublishPublishingActivityRequestSourceType))]
	[KnownType(typeof(CpSnippet))]
	[KnownType(typeof(cpTimeZoneInfo))]
	[KnownType(typeof(cpWorkflowActionRequired))]
	[KnownType(typeof(CreateAssetShortcutResponse))]
	[KnownType(typeof(CreateAssetsShortcutRequest))]
	[KnownType(typeof(CreateAssetsShortcutResponse))]
	[KnownType(typeof(CreateBranchRequest))]
	[KnownType(typeof(CreateBranchResponse))]
	[KnownType(typeof(CreateCollectionResponse))]
	[KnownType(typeof(CreateCustomClassResponse))]
	[KnownType(typeof(CreateDashboardResponse))]
	[KnownType(typeof(CreateExternalLibraryRequest))]
	[KnownType(typeof(CreateExternalLibraryResponse))]
	[KnownType(typeof(CreateFileByModelIdRequest))]
	[KnownType(typeof(CreateFileByModelIdResponse))]
	[KnownType(typeof(CreateFileRequest))]
	[KnownType(typeof(CreateFileResponse))]
	[KnownType(typeof(CreateFolderByModelIdRequest))]
	[KnownType(typeof(CreateFolderByModelIdResponse))]
	[KnownType(typeof(CreateFolderRequest))]
	[KnownType(typeof(CreateFolderResponse))]
	[KnownType(typeof(CreateLibraryRequest))]
	[KnownType(typeof(CreateLibraryResponse))]
	[KnownType(typeof(CreateProfileRequest))]
	[KnownType(typeof(CreateProfileResponse))]
	[KnownType(typeof(CreateProjectRequest))]
	[KnownType(typeof(CreateProjectResponse))]
	[KnownType(typeof(CreateSiteRootRequest))]
	[KnownType(typeof(CreateSiteRootResponse))]
	[KnownType(typeof(CreateTemplateFileRequest))]
	[KnownType(typeof(CreateTemplateFileResponse))]
	[KnownType(typeof(CreateTemplateFolderRequest))]
	[KnownType(typeof(CreateTemplateFolderResponse))]
	[KnownType(typeof(CreateTemplateRequest))]
	[KnownType(typeof(CreateTemplateResponse))]
	[KnownType(typeof(CreateUserRequest))]
	[KnownType(typeof(CreateUserResponse))]
	[KnownType(typeof(DebugMessage))]
	[KnownType(typeof(DeleteConnectorRequest))]
	[KnownType(typeof(DeleteConnectorResponse))]
	[KnownType(typeof(DeleteEmailSenderRequest))]
	[KnownType(typeof(DeleteEmailSenderResponse))]
	[KnownType(typeof(DeleteGroupRequest))]
	[KnownType(typeof(DeleteGroupResponse))]
	[KnownType(typeof(DeletePackageConfigDataRequest))]
	[KnownType(typeof(DeletePackageConfigDataResponse))]
	[KnownType(typeof(DeleteUserRequest))]
	[KnownType(typeof(DeleteUserResponse))]
	[KnownType(typeof(DeleteUsersRequest))]
	[KnownType(typeof(DeleteUsersResponse))]
	[KnownType(typeof(DeleteWorkflowResponse))]
	[KnownType(typeof(DeleteWorkflowsResponse))]
	[KnownType(typeof(DemandBaseDataRow))]
	[KnownType(typeof(DependencyType))]
	[KnownType(typeof(DeploymentRecord))]
	[KnownType(typeof(DeploymentType))]
	[KnownType(typeof(DeviceLayoutConfigData))]
	[KnownType(typeof(DeviceLayoutData))]
	[KnownType(typeof(DiagnosticsErrorData))]
	[KnownType(typeof(DiagnosticsReportData))]
	[KnownType(typeof(DownloadAssetResponse))]
	[KnownType(typeof(DownloadAssetsRequest))]
	[KnownType(typeof(DownloadAssetsResponse))]
	[KnownType(typeof(DownloadBytesRequest))]
	[KnownType(typeof(DownloadResponse))]
	[KnownType(typeof(EditModeType))]
	[KnownType(typeof(EmailAttachment))]
	[KnownType(typeof(EmailSender))]
	[KnownType(typeof(EmailValidationStatus))]
	[KnownType(typeof(eResultCodes))]
	[KnownType(typeof(ExecuteWorkflowCommandRequest))]
	[KnownType(typeof(ExecuteWorkflowCommandResponse))]
	[KnownType(typeof(FacebookInsightsAccount))]
	[KnownType(typeof(FacebookInsightsData))]
	[KnownType(typeof(FilenameFilterData))]
	[KnownType(typeof(FinishDownloadAssetRequest))]
	[KnownType(typeof(FinishDownloadAssetResponse))]
	[KnownType(typeof(FinishSelectImageRequest))]
	[KnownType(typeof(FinishSelectImageResponse))]
	[KnownType(typeof(FinishUploadAssetRequest))]
	[KnownType(typeof(FinishUploadAssetResponse))]
	[KnownType(typeof(FinishUploadAttachmentRequest))]
	[KnownType(typeof(FinishUploadAttachmentResponse))]
	[KnownType(typeof(FinishUploadAvatarRequest))]
	[KnownType(typeof(FinishUploadAvatarResponse))]
	[KnownType(typeof(FolderOptionData))]
	[KnownType(typeof(ForgotPasswordResponse))]
	[KnownType(typeof(FtpServerData))]
	[KnownType(typeof(GeneralConfigData))]
	[KnownType(typeof(GeneralPropertiesResponse))]
	[KnownType(typeof(GeneralWCOConfigData))]
	[KnownType(typeof(GetActiveStandardsReportResponse))]
	[KnownType(typeof(GetAdvancedSearchOptionsResponse))]
	[KnownType(typeof(GetAlertConfigDataResponse))]
	[KnownType(typeof(GetAssetAndChildrenByIdResponse))]
	[KnownType(typeof(GetAssetByGoToQueryRequest))]
	[KnownType(typeof(GetAssetByGoToQueryResponse))]
	[KnownType(typeof(GetAssetByPathResponse))]
	[KnownType(typeof(GetAssetFieldsResponse))]
	[KnownType(typeof(GetAssetListRequest))]
	[KnownType(typeof(GetAssetListResponse))]
	[KnownType(typeof(GetAssetMetaDataResponse))]
	[KnownType(typeof(GetAssetPathByIdResponse))]
	[KnownType(typeof(GetAssetPublishHistoryResponse))]
	[KnownType(typeof(GetAssetRefreshReportResponse))]
	[KnownType(typeof(GetAssetResponse))]
	[KnownType(typeof(GetAssetScheduleResponse))]
	[KnownType(typeof(GetAssetVersionsResponse))]
	[KnownType(typeof(GetAuditReportRequest))]
	[KnownType(typeof(GetBoxAccountsRequest))]
	[KnownType(typeof(GetBoxAccountsResponse))]
	[KnownType(typeof(GetChildStatesRequest))]
	[KnownType(typeof(GetChildStatesResponse))]
	[KnownType(typeof(GetCollectionsAssetListResponse))]
	[KnownType(typeof(GetCollectionsResponse))]
	[KnownType(typeof(GetConnectorConfigDataResponse))]
	[KnownType(typeof(GetConnectorRequest))]
	[KnownType(typeof(GetConnectorResponse))]
	[KnownType(typeof(GetCPAvatarsResponse))]
	[KnownType(typeof(GetDashboardAssetsResponse))]
	[KnownType(typeof(GetDebugMessagesResponse))]
	[KnownType(typeof(GetDemandbaseDataRequest))]
	[KnownType(typeof(GetDemandbaseDataResponse))]
	[KnownType(typeof(GetDepartmentsResponse))]
	[KnownType(typeof(GetDiagnosticsReportDataResponse))]
	[KnownType(typeof(GetDropBoxAccountsRequest))]
	[KnownType(typeof(GetDropBoxAccountsResponse))]
	[KnownType(typeof(GetEmailSendersResponse))]
	[KnownType(typeof(GetFacebookInsightsDataRequest))]
	[KnownType(typeof(GetFacebookInsightsDataResponse))]
	[KnownType(typeof(GetFileOptionsResponse))]
	[KnownType(typeof(GetFolderAssetFieldsResponse))]
	[KnownType(typeof(GetFolderOptionsResponse))]
	[KnownType(typeof(GetFtpServersDataResponse))]
	[KnownType(typeof(GetGeneralConfigDataResponse))]
	[KnownType(typeof(GetGeneralWCOConfigDataResponse))]
	[KnownType(typeof(GetGoogleAnalyticsAccountsRequest))]
	[KnownType(typeof(GetGoogleAnalyticsAccountsResponse))]
	[KnownType(typeof(GetGoogleAnalyticsDataRequest))]
	[KnownType(typeof(GetGoogleAnalyticsDataResponse))]
	[KnownType(typeof(GetGoogleAnalyticsProfilesRequest))]
	[KnownType(typeof(GetGoogleAnalyticsProfilesResponse))]
	[KnownType(typeof(GetGoogleAnalyticsPropertiesRequest))]
	[KnownType(typeof(GetGoogleAnalyticsPropertiesResponse))]
	[KnownType(typeof(GetGoogleDriveRequest))]
	[KnownType(typeof(GetGoogleDriveResponse))]
	[KnownType(typeof(GetGroupsConfigDataRequest))]
	[KnownType(typeof(GetGroupsConfigDataResponse))]
	[KnownType(typeof(GetGroupsDataResponse))]
	[KnownType(typeof(GetHelpAssetsResponse))]
	[KnownType(typeof(GetHttpServersDataResponse))]
	[KnownType(typeof(GetJobActivityRequest))]
	[KnownType(typeof(GetJobActivityResponse))]
	[KnownType(typeof(GetJobQueueItemResponse))]
	[KnownType(typeof(GetJobQueueItemsResponse))]
	[KnownType(typeof(GetLayoutNamesResponse))]
	[KnownType(typeof(GetLayoutsResponse))]
	[KnownType(typeof(GetLibraryFilesCDCInfo))]
	[KnownType(typeof(GetLibraryFilesCDCRequest))]
	[KnownType(typeof(GetLibraryFilesCDCResponse))]
	[KnownType(typeof(GetLibraryFilesZipCDCRequest))]
	[KnownType(typeof(GetLibraryFilesZipCDCResponse))]
	[KnownType(typeof(GetLocationsResponse))]
	[KnownType(typeof(GetMaintenanceMessageResult))]
	[KnownType(typeof(GetManagedFacebookAccountsRequest))]
	[KnownType(typeof(GetManagedFacebookAccountsResponse))]
	[KnownType(typeof(GetMenuConfigDataResponse))]
	[KnownType(typeof(GetModelPropertiesResponse))]
	[KnownType(typeof(GetOdbcServersDataResponse))]
	[KnownType(typeof(GetOrphanReportResponse))]
	[KnownType(typeof(GetOrphanReportServerDataResponse))]
	[KnownType(typeof(GetOutputURLRequest))]
	[KnownType(typeof(GetOutputURLResponse))]
	[KnownType(typeof(GetPasswordPolicyResponse))]
	[KnownType(typeof(GetPerformanceDataRequest))]
	[KnownType(typeof(GetPerformanceDataResponse))]
	[KnownType(typeof(GetPluginBodyRequest))]
	[KnownType(typeof(GetPluginBodyResponse))]
	[KnownType(typeof(GetPreAuthDataResponse))]
	[KnownType(typeof(GetProviderInfoResponse))]
	[KnownType(typeof(GetProviderSettingsConfigDataResponse))]
	[KnownType(typeof(GetProvidersResponse))]
	[KnownType(typeof(GetPublishHistoryResponse))]
	[KnownType(typeof(GetPublishingActivity2Request))]
	[KnownType(typeof(GetPublishingActivity2Response))]
	[KnownType(typeof(GetPublishingPackageSummaryRequest))]
	[KnownType(typeof(GetPublishingPackageSummaryResponse))]
	[KnownType(typeof(GetPublishingServersDataResponse))]
	[KnownType(typeof(GetPublishingServersMetaDataResponse))]
	[KnownType(typeof(GetPublishingServersResponse))]
	[KnownType(typeof(GetRelatedAssetsRequest))]
	[KnownType(typeof(GetRelatedAssetsResponse))]
	[KnownType(typeof(GetSecurityConfigDataResponse))]
	[KnownType(typeof(GetSelectListsResponse))]
	[KnownType(typeof(GetSite24x7Request))]
	[KnownType(typeof(GetSite24x7Response))]
	[KnownType(typeof(GetSiteRootPropertiesResponse))]
	[KnownType(typeof(GetSmtpServersDataResponse))]
	[KnownType(typeof(GetSoapServersDataResponse))]
	[KnownType(typeof(GetStatusFromActiveStandardsRequest))]
	[KnownType(typeof(GetStatusFromActiveStandardsResponse))]
	[KnownType(typeof(GetSystemHistoryResponse))]
	[KnownType(typeof(GetSystemVariablesDataResponse))]
	[KnownType(typeof(GetTasksResponse))]
	[KnownType(typeof(GetTemplatesFolderResponse))]
	[KnownType(typeof(GetTitlesResponse))]
	[KnownType(typeof(GetTwitterAuthLinkResponse))]
	[KnownType(typeof(GetUrlFilenameFiltersResponse))]
	[KnownType(typeof(GetUserDataResponse))]
	[KnownType(typeof(GetUserHelpResponse))]
	[KnownType(typeof(GetUserPreferencesDataResponse))]
	[KnownType(typeof(GetUsersConfigDataRequest))]
	[KnownType(typeof(GetUsersConfigDataResponse))]
	[KnownType(typeof(GetWorkflowListByFolderResponse))]
	[KnownType(typeof(GetWorkflowPropertiesResponse))]
	[KnownType(typeof(GetWorkflowsResponse))]
	[KnownType(typeof(GoogleAnalyticsAccount))]
	[KnownType(typeof(GoogleAnalyticsData))]
	[KnownType(typeof(Group))]
	[KnownType(typeof(GroupData))]
	[KnownType(typeof(HeartbeatResponse))]
	[KnownType(typeof(HttpServerData))]
	[KnownType(typeof(IconType))]
	[KnownType(typeof(InstrumentEntity))]
	[KnownType(typeof(InstrumentSettings))]
	[KnownType(typeof(IsOutputWebCaptureCompleteResponse))]
	[KnownType(typeof(JobActivity))]
	[KnownType(typeof(JobData))]
	[KnownType(typeof(JobItem))]
	[KnownType(typeof(JobQueue))]
	[KnownType(typeof(JobState))]
	[KnownType(typeof(JobType))]
	[KnownType(typeof(CrownPeak.AccessAPI.JoinType))]
	[KnownType(typeof(LayoutData))]
	[KnownType(typeof(LibraryModificationTimes))]
	[KnownType(typeof(LightAsset))]
	[KnownType(typeof(LightAssetField))]
	[KnownType(typeof(LightAssetFieldList))]
	[KnownType(typeof(LoginModeType))]
	[KnownType(typeof(LogoutReason))]
	[KnownType(typeof(LogoutRequest))]
	[KnownType(typeof(LogoutResponse))]
	[KnownType(typeof(MenuShortCutData))]
	[KnownType(typeof(MoveAssetRequest))]
	[KnownType(typeof(MoveAssetResponse))]
	[KnownType(typeof(MoveAssetsRequest))]
	[KnownType(typeof(MoveAssetsResponse))]
	[KnownType(typeof(OdbcServerData))]
	[KnownType(typeof(OpenTemplateCDCRequest))]
	[KnownType(typeof(OpenTemplateCDCResponse))]
	[KnownType(typeof(OrderType))]
	[KnownType(typeof(OrphanAuditData))]
	[KnownType(typeof(OrphanReportServerData))]
	[KnownType(typeof(Package))]
	[KnownType(typeof(PackageInfo))]
	[KnownType(typeof(PasswordPolicyConfig))]
	[KnownType(typeof(PreCreateJobRequest))]
	[KnownType(typeof(PreCreateJobResponse))]
	[KnownType(typeof(PreferenceData))]
	[KnownType(typeof(PreferenceDataType))]
	[KnownType(typeof(PrepareDownloadAssetRequest))]
	[KnownType(typeof(PrepareDownloadAuditCSVResponse))]
	[KnownType(typeof(PrepareDownloadResponse))]
	[KnownType(typeof(PrepareUploadAssetRequest))]
	[KnownType(typeof(PrepareUploadResponse))]
	[KnownType(typeof(ProjectLibrary))]
	[KnownType(typeof(ProjectLibraryFile))]
	[KnownType(typeof(ProjectLibraryZip))]
	[KnownType(typeof(Provider))]
	[KnownType(typeof(ProviderSettings))]
	[KnownType(typeof(ProviderSettingsConfigData))]
	[KnownType(typeof(PublishAuditData))]
	[KnownType(typeof(PublishedFile))]
	[KnownType(typeof(PublishedPageData))]
	[KnownType(typeof(PublishedUrl))]
	[KnownType(typeof(PublishInfo))]
	[KnownType(typeof(PublishingActivity))]
	[KnownType(typeof(PublishingActivity2))]
	[KnownType(typeof(PublishingActivityCounts))]
	[KnownType(typeof(PublishingActivityListResponse))]
	[KnownType(typeof(PublishingActivityRequest))]
	[KnownType(typeof(PublishingDetailData))]
	[KnownType(typeof(PublishingLog))]
	[KnownType(typeof(PublishingPackageSummary))]
	[KnownType(typeof(PublishingPropertiesResponse))]
	[KnownType(typeof(PublishingServer))]
	[KnownType(typeof(PublishingServerData))]
	[KnownType(typeof(PublishingServerMetaData))]
	[KnownType(typeof(PublishingSession))]
	[KnownType(typeof(PublishingSessionData))]
	[KnownType(typeof(PublishListResponse))]
	[KnownType(typeof(PublishPath))]
	[KnownType(typeof(PublishRefreshListResponse))]
	[KnownType(typeof(PublishRefreshResponse))]
	[KnownType(typeof(PublishResponse))]
	[KnownType(typeof(QuickSearchRequest))]
	[KnownType(typeof(QuickSearchResponse))]
	[KnownType(typeof(RecompileTemplatesRequest))]
	[KnownType(typeof(RecompileTemplatesResponse))]
	[KnownType(typeof(RecompileType))]
	[KnownType(typeof(ReferencedLibrary))]
	[KnownType(typeof(RefreshPublishingPackageRequest))]
	[KnownType(typeof(RefreshPublishingPackageResponse))]
	[KnownType(typeof(RelatedAssetType))]
	[KnownType(typeof(RenameAssetRequest))]
	[KnownType(typeof(RenameAssetResponse))]
	[KnownType(typeof(RenameAssetsRequest))]
	[KnownType(typeof(RenameAssetsResponse))]
	[KnownType(typeof(RenderInputTemplateResponse))]
	[KnownType(typeof(ReportData))]
	[KnownType(typeof(ReportDataTemplate))]
	[KnownType(typeof(ReportResponse))]
	[KnownType(typeof(ReportRow))]
	[KnownType(typeof(ReportType))]
	[KnownType(typeof(RepositoryServer))]
	[KnownType(typeof(ResultClass))]
	[KnownType(typeof(RevertAssetVersionResponse))]
	[KnownType(typeof(RouteAssetRequest))]
	[KnownType(typeof(RouteAssetResponse))]
	[KnownType(typeof(RouteAssetsRequest))]
	[KnownType(typeof(RouteAssetsResponse))]
	[KnownType(typeof(Rule))]
	[KnownType(typeof(RuleType))]
	[KnownType(typeof(ScheduleData))]
	[KnownType(typeof(ScheduleFrequency))]
	[KnownType(typeof(SearchField))]
	[KnownType(typeof(SearchFields))]
	[KnownType(typeof(SearchFieldType))]
	[KnownType(typeof(SecurityConfigData))]
	[KnownType(typeof(SendCDCLogRequest))]
	[KnownType(typeof(SendCDCLogResponse))]
	[KnownType(typeof(SendToActiveStandardsRequest))]
	[KnownType(typeof(SendToActiveStandardsResponse))]
	[KnownType(typeof(SetAlertConfigDataRequest))]
	[KnownType(typeof(SetAlertConfigDataResponse))]
	[KnownType(typeof(SetAssetDeletedRequest))]
	[KnownType(typeof(SetAssetDeletedResponse))]
	[KnownType(typeof(SetAssetFieldsRequest))]
	[KnownType(typeof(SetAssetFlaggedResponse))]
	[KnownType(typeof(SetAssetHiddenResponse))]
	[KnownType(typeof(SetAssetMetaDataRequest))]
	[KnownType(typeof(SetAssetMetaDataResponse))]
	[KnownType(typeof(SetAssetScheduleRequest))]
	[KnownType(typeof(SetAssetScheduleResponse))]
	[KnownType(typeof(SetAssetsDeletedRequest))]
	[KnownType(typeof(SetAssetsDeletedResponse))]
	[KnownType(typeof(SetAssetsFieldsRequest))]
	[KnownType(typeof(SetAssetsFlaggedResponse))]
	[KnownType(typeof(SetAssetsHiddenResponse))]
	[KnownType(typeof(SetAssetsMetaDataRequest))]
	[KnownType(typeof(SetAssetsMetaDataResponse))]
	[KnownType(typeof(SetAsSiteRootRequest))]
	[KnownType(typeof(SetAsSiteRootResponse))]
	[KnownType(typeof(SetConnectorConfigDataRequest))]
	[KnownType(typeof(SetConnectorConfigDataResponse))]
	[KnownType(typeof(SetFileOptionsResponse))]
	[KnownType(typeof(SetFolderOptionsResponse))]
	[KnownType(typeof(SetGeneralConfigDataResponse))]
	[KnownType(typeof(SetGeneralWCOConfigDataResponse))]
	[KnownType(typeof(SetHttpServerDataRequest))]
	[KnownType(typeof(SetHttpServerDataResponse))]
	[KnownType(typeof(SetMenuConfigDataRequest))]
	[KnownType(typeof(SetMenuConfigDataResponse))]
	[KnownType(typeof(SetMenuShortcutRequest))]
	[KnownType(typeof(SetMenuShortcutResponse))]
	[KnownType(typeof(SetModelPropertiesResponse))]
	[KnownType(typeof(SetOdbcServerDataRequest))]
	[KnownType(typeof(SetOdbcServerDataResponse))]
	[KnownType(typeof(SetPasswordPolicyRequest))]
	[KnownType(typeof(SetPasswordPolicyResponse))]
	[KnownType(typeof(SetPasswordResponse))]
	[KnownType(typeof(SetProviderSettingsConfigDataResponse))]
	[KnownType(typeof(SetPublishingServerDataRequest))]
	[KnownType(typeof(SetPublishingServerDataResponse))]
	[KnownType(typeof(SetPublishingServerMetaDataRequest))]
	[KnownType(typeof(SetPublishingServerMetaDataResponse))]
	[KnownType(typeof(SetRepositoryServerDataRequest))]
	[KnownType(typeof(SetRepositoryServerDataResponse))]
	[KnownType(typeof(SetSecurityConfigDataResponse))]
	[KnownType(typeof(SetSelectListResponse))]
	[KnownType(typeof(SetSiteRootPropertiesRequest))]
	[KnownType(typeof(SetSiteRootPropertiesResponse))]
	[KnownType(typeof(SetSmtpServerDataRequest))]
	[KnownType(typeof(SetSmtpServerDataResponse))]
	[KnownType(typeof(SetSystemVariablesDataRequest))]
	[KnownType(typeof(SetSystemVariablesDataResponse))]
	[KnownType(typeof(SetUrlFilenameFiltersRequest))]
	[KnownType(typeof(SetUrlFilenameFiltersResponse))]
	[KnownType(typeof(SetUserDataRequest))]
	[KnownType(typeof(SetUserDataResponse))]
	[KnownType(typeof(SetUserPreferenceDataRequest))]
	[KnownType(typeof(SetUserPreferenceDataResponse))]
	[KnownType(typeof(SetWorkflowPropertiesResponse))]
	[KnownType(typeof(SetWorklistPreferenceResponse))]
	[KnownType(typeof(Site24x7MonitorData))]
	[KnownType(typeof(SiteRootProperties))]
	[KnownType(typeof(SmtpServerData))]
	[KnownType(typeof(Snippet))]
	[KnownType(typeof(SnippetAssociation))]
	[KnownType(typeof(SnippetInfo))]
	[KnownType(typeof(SnippetList))]
	[KnownType(typeof(SnippetOverview))]
	[KnownType(typeof(SnippetVariantTestsData))]
	[KnownType(typeof(SnippetVariantType))]
	[KnownType(typeof(SoapServerData))]
	[KnownType(typeof(SortCriterion))]
	[KnownType(typeof(SortHeaderOptionData))]
	[KnownType(typeof(StartFindOrphanReportRequest))]
	[KnownType(typeof(StartFindOrphanReportResponse))]
	[KnownType(typeof(StatusData))]
	[KnownType(typeof(StatusTransition))]
	[KnownType(typeof(StopPublishingSessionResponse))]
	[KnownType(typeof(StopTemplateDebuggingResponse))]
	[KnownType(typeof(CrownPeak.AccessAPI.Stopwatch))]
	[KnownType(typeof(SubmitSuportTicketRequest))]
	[KnownType(typeof(SystemAuditData))]
	[KnownType(typeof(SystemSummaryReportData))]
	[KnownType(typeof(SystemSummaryReportResponse))]
	[KnownType(typeof(SystemVariableData))]
	[KnownType(typeof(TargetGroup))]
	[KnownType(typeof(TemplateProfile))]
	[KnownType(typeof(TemplatePropertiesResponse))]
	[KnownType(typeof(TemplateReportResponse))]
	[KnownType(typeof(TestConnectorRequest))]
	[KnownType(typeof(TestConnectorResponse))]
	[KnownType(typeof(Thumbnail))]
	[KnownType(typeof(UnBranchRequest))]
	[KnownType(typeof(UnBranchResponse))]
	[KnownType(typeof(UnlockAssetResponse))]
	[KnownType(typeof(UnlockAssetsRequest))]
	[KnownType(typeof(UpdateConnectorRequest))]
	[KnownType(typeof(UpdateConnectorResponse))]
	[KnownType(typeof(UpdatePackageConfigDataRequest))]
	[KnownType(typeof(UpdatePackageConfigDataResponse))]
	[KnownType(typeof(UpdateServerMetaConfigRequest))]
	[KnownType(typeof(UpdateServerMetaConfigResponse))]
	[KnownType(typeof(UploadBytesRequest))]
	[KnownType(typeof(UploadResponse))]
	[KnownType(typeof(UrlFilterData))]
	[KnownType(typeof(UserData))]
	[KnownType(typeof(UserDataType))]
	[KnownType(typeof(UserLoginReportData))]
	[KnownType(typeof(UserLoginReportResponse))]
	[KnownType(typeof(ValidateEmailSenderRequest))]
	[KnownType(typeof(ValidateEmailSenderResponse))]
	[KnownType(typeof(VariantAsset))]
	[KnownType(typeof(VerifyBuildRequest))]
	[KnownType(typeof(VerifyBuildResponse))]
	[KnownType(typeof(VersionReportData))]
	[KnownType(typeof(ViewMenuConfigData))]
	[KnownType(typeof(VisibilityType))]
	[KnownType(typeof(WCOAddAndDeleteVariantsRequest))]
	[KnownType(typeof(WCOAddAndDeleteVariantsResponse))]
	[KnownType(typeof(WCOAddSnippetResponse))]
	[KnownType(typeof(WCOAddVariantResponse))]
	[KnownType(typeof(WCOAnalyticsSiteData))]
	[KnownType(typeof(WCOBeaconSiteData))]
	[KnownType(typeof(WCOCollectionData))]
	[KnownType(typeof(WCOCreateConversionUrlRequest))]
	[KnownType(typeof(WCOCreateConversionUrlResponse))]
	[KnownType(typeof(WCODeleteVariantFromCmsResponse))]
	[KnownType(typeof(WCODetachSnippetResponse))]
	[KnownType(typeof(WCOGetCollectionsAndSnippetsResponse))]
	[KnownType(typeof(WCOGetCountsResponse))]
	[KnownType(typeof(WCOGetFormBuilderUrlResponse))]
	[KnownType(typeof(WCOGetOutputUrlResponse))]
	[KnownType(typeof(WCOGetProfilesByAssetIdResponse))]
	[KnownType(typeof(WCOGetSnippetsResponse))]
	[KnownType(typeof(WCOGetSnippetVariantTestsDataResponse))]
	[KnownType(typeof(WCOGetStatsCountsResponse))]
	[KnownType(typeof(WCOGetTargetingGroupsResponse))]
	[KnownType(typeof(WCOGetVariantCount))]
	[KnownType(typeof(WCOGetVariantCountsResponse))]
	[KnownType(typeof(WCOGetVariantOverviewResponse))]
	[KnownType(typeof(WCOGetVariantsResponse))]
	[KnownType(typeof(WCOPageData))]
	[KnownType(typeof(WCOSaveSelectionResponse))]
	[KnownType(typeof(WcoSnippetAddition))]
	[KnownType(typeof(WcoSnippetClone))]
	[KnownType(typeof(WcoSnippetCloneData))]
	[KnownType(typeof(WCOSnippetData))]
	[KnownType(typeof(WcoSnippetDetachment))]
	[KnownType(typeof(WCOTargetGroupData))]
	[KnownType(typeof(WCOUpdateVariantResponse))]
	[KnownType(typeof(WcoVariantAddition))]
	[KnownType(typeof(WcoVariantChangeset))]
	[KnownType(typeof(WcoVariantDeletion))]
	[KnownType(typeof(WcoVariantSelection))]
	[KnownType(typeof(Workflow))]
	[KnownType(typeof(WorkflowCommandData))]
	[KnownType(typeof(WorkflowData))]
	[KnownType(typeof(WorkflowListItem))]
	[KnownType(typeof(WorkflowScheduleItem))]
	[KnownType(typeof(WorkflowStepCommandsData))]
	[KnownType(typeof(WorklistAsset))]
	[KnownType(typeof(WorklistAssetAndFields))]
	[KnownType(typeof(WorklistPreferenceData))]
	[KnownType(typeof(WSResultClass))]
	[KnownType(typeof(WysiwygEditorType))]
	[KnownType(typeof(Dictionary<CountType, ICollection<CountStatSummary>>))]
	[KnownType(typeof(Dictionary<PreferenceDataType, string>))]
	[KnownType(typeof(Dictionary<UserDataType, string>))]
	[KnownType(typeof(Dictionary<Guid, WCOTargetGroupData>))]
	[KnownType(typeof(Dictionary<Guid, ICollection<WCOSnippetData>>))]
	[KnownType(typeof(Dictionary<int, ActionData>))]
	[KnownType(typeof(Dictionary<int, ActiveStandardsData>))]
	[KnownType(typeof(Dictionary<int, CopyAssetResponse>))]
	[KnownType(typeof(Dictionary<int, cpPublishPublishingActivityDetailRequest>))]
	[KnownType(typeof(Dictionary<int, CreateAssetShortcutResponse>))]
	[KnownType(typeof(Dictionary<int, MoveAssetResponse>))]
	[KnownType(typeof(Dictionary<int, PublishRefreshResponse>))]
	[KnownType(typeof(Dictionary<int, PublishResponse>))]
	[KnownType(typeof(Dictionary<int, RenameAssetResponse>))]
	[KnownType(typeof(Dictionary<int, ResultClass>))]
	[KnownType(typeof(Dictionary<int, SetAssetDeletedResponse>))]
	[KnownType(typeof(Dictionary<int, SetAssetFlaggedResponse>))]
	[KnownType(typeof(Dictionary<int, SetAssetHiddenResponse>))]
	[KnownType(typeof(Dictionary<int, SetAssetMetaDataResponse>))]
	[KnownType(typeof(Dictionary<int, StatusData>))]
	[KnownType(typeof(Dictionary<int, WorkflowData>))]
	[KnownType(typeof(Dictionary<int, string>))]
	[KnownType(typeof(Dictionary<string, CancelUploadResponse>))]
	[KnownType(typeof(Dictionary<string, Dictionary<string, string>>))]
	[KnownType(typeof(Dictionary<string, int>))]
	[KnownType(typeof(Dictionary<string, string>))]
	[KnownType(typeof(ICollection<ActiveStandardsCheckpoint>))]
	[KnownType(typeof(ICollection<ActivityUserData>))]
	[KnownType(typeof(ICollection<AlertActionType>))]
	[KnownType(typeof(ICollection<ApprovedHostname>))]
	[KnownType(typeof(ICollection<AssetChangeset>))]
	[KnownType(typeof(ICollection<AssetPropertyNames>))]
	[KnownType(typeof(ICollection<AssetPublishAuditData>))]
	[KnownType(typeof(ICollection<AssetRefreshReportData>))]
	[KnownType(typeof(ICollection<AssetRenderPerformanceData>))]
	[KnownType(typeof(ICollection<AssetRenderPerformanceHistoryItem>))]
	[KnownType(typeof(ICollection<AssetResult>))]
	[KnownType(typeof(ICollection<AssetsField>))]
	[KnownType(typeof(ICollection<AssetsMeta>))]
	[KnownType(typeof(ICollection<AssetStatus>))]
	[KnownType(typeof(ICollection<AssetWCOChangeset>))]
	[KnownType(typeof(ICollection<AssetWorkflowSchedule>))]
	[KnownType(typeof(ICollection<BehavioralRule>))]
	[KnownType(typeof(ICollection<CallEntity>))]
	[KnownType(typeof(ICollection<CancelUploadRequest>))]
	[KnownType(typeof(ICollection<CrownPeak.AccessAPI.Comparison>))]
	[KnownType(typeof(ICollection<ConnectorAsset>))]
	[KnownType(typeof(ICollection<ConnectorConfigData>))]
	[KnownType(typeof(ICollection<ConnectorSelectorData>))]
	[KnownType(typeof(ICollection<CountStatSummary>))]
	[KnownType(typeof(ICollection<CpCompilerError>))]
	[KnownType(typeof(ICollection<cpKVPOfintstring>))]
	[KnownType(typeof(ICollection<cpKVPOfSearchFieldTypeArrayOfComparisonv_SQRvoIg>))]
	[KnownType(typeof(ICollection<cpListscpKeyValuePair>))]
	[KnownType(typeof(ICollection<CpSnippet>))]
	[KnownType(typeof(ICollection<cpTimeZoneInfo>))]
	[KnownType(typeof(ICollection<DebugMessage>))]
	[KnownType(typeof(ICollection<DemandBaseDataRow>))]
	[KnownType(typeof(ICollection<DeploymentRecord>))]
	[KnownType(typeof(ICollection<DeviceLayoutConfigData>))]
	[KnownType(typeof(ICollection<DeviceLayoutData>))]
	[KnownType(typeof(ICollection<DiagnosticsErrorData>))]
	[KnownType(typeof(ICollection<DiagnosticsReportData>))]
	[KnownType(typeof(ICollection<EmailAttachment>))]
	[KnownType(typeof(ICollection<EmailSender>))]
	[KnownType(typeof(ICollection<FacebookInsightsAccount>))]
	[KnownType(typeof(ICollection<FilenameFilterData>))]
	[KnownType(typeof(ICollection<FilterExpression>))]
	[KnownType(typeof(ICollection<FolderOptionData>))]
	[KnownType(typeof(ICollection<FtpServerData>))]
	[KnownType(typeof(ICollection<GoogleAnalyticsAccount>))]
	[KnownType(typeof(ICollection<GroupData>))]
	[KnownType(typeof(ICollection<HttpServerData>))]
	[KnownType(typeof(ICollection<InstrumentEntity>))]
	[KnownType(typeof(ICollection<JobData>))]
	[KnownType(typeof(ICollection<JobItem>))]
	[KnownType(typeof(ICollection<JobQueue>))]
	[KnownType(typeof(ICollection<LayoutData>))]
	[KnownType(typeof(ICollection<LibraryModificationTimes>))]
	[KnownType(typeof(ICollection<LightAsset>))]
	[KnownType(typeof(ICollection<LightAssetField>))]
	[KnownType(typeof(ICollection<LightAssetFieldList>))]
	[KnownType(typeof(ICollection<MenuShortCutData>))]
	[KnownType(typeof(ICollection<OdbcServerData>))]
	[KnownType(typeof(ICollection<OrphanAuditData>))]
	[KnownType(typeof(ICollection<OrphanReportServerData>))]
	[KnownType(typeof(ICollection<Package>))]
	[KnownType(typeof(ICollection<PackageInfo>))]
	[KnownType(typeof(ICollection<ProjectLibrary>))]
	[KnownType(typeof(ICollection<ProjectLibraryFile>))]
	[KnownType(typeof(ICollection<ProjectLibraryZip>))]
	[KnownType(typeof(ICollection<Provider>))]
	[KnownType(typeof(ICollection<PublishAuditData>))]
	[KnownType(typeof(ICollection<PublishedPageData>))]
	[KnownType(typeof(ICollection<PublishInfo>))]
	[KnownType(typeof(ICollection<PublishingActivityCounts>))]
	[KnownType(typeof(ICollection<PublishingDetailData>))]
	[KnownType(typeof(ICollection<PublishingLog>))]
	[KnownType(typeof(ICollection<PublishingServer>))]
	[KnownType(typeof(ICollection<PublishingServerData>))]
	[KnownType(typeof(ICollection<PublishingServerMetaData>))]
	[KnownType(typeof(ICollection<PublishingSession>))]
	[KnownType(typeof(ICollection<PublishingSessionData>))]
	[KnownType(typeof(ICollection<ReferencedLibrary>))]
	[KnownType(typeof(ICollection<RenameAssetRequest>))]
	[KnownType(typeof(ICollection<ReportDataTemplate>))]
	[KnownType(typeof(ICollection<ReportRow>))]
	[KnownType(typeof(ICollection<Rule>))]
	[KnownType(typeof(ICollection<SearchField>))]
	[KnownType(typeof(ICollection<SetAssetMetaDataRequest>))]
	[KnownType(typeof(ICollection<Site24x7MonitorData>))]
	[KnownType(typeof(ICollection<SmtpServerData>))]
	[KnownType(typeof(ICollection<Snippet>))]
	[KnownType(typeof(ICollection<SnippetAssociation>))]
	[KnownType(typeof(ICollection<SnippetInfo>))]
	[KnownType(typeof(ICollection<SnippetVariantTestsData>))]
	[KnownType(typeof(ICollection<SoapServerData>))]
	[KnownType(typeof(ICollection<SortCriterion>))]
	[KnownType(typeof(ICollection<StatusTransition>))]
	[KnownType(typeof(ICollection<SystemAuditData>))]
	[KnownType(typeof(ICollection<SystemVariableData>))]
	[KnownType(typeof(ICollection<TargetGroup>))]
	[KnownType(typeof(ICollection<Thumbnail>))]
	[KnownType(typeof(ICollection<UrlFilterData>))]
	[KnownType(typeof(ICollection<UserData>))]
	[KnownType(typeof(ICollection<UserLoginReportData>))]
	[KnownType(typeof(ICollection<VariantAsset>))]
	[KnownType(typeof(ICollection<VersionReportData>))]
	[KnownType(typeof(ICollection<ViewMenuConfigData>))]
	[KnownType(typeof(ICollection<WCOAnalyticsSiteData>))]
	[KnownType(typeof(ICollection<WCOBeaconSiteData>))]
	[KnownType(typeof(ICollection<WCOCollectionData>))]
	[KnownType(typeof(ICollection<WCOGetVariantCount>))]
	[KnownType(typeof(ICollection<WCOPageData>))]
	[KnownType(typeof(ICollection<WcoSnippetAddition>))]
	[KnownType(typeof(ICollection<WcoSnippetClone>))]
	[KnownType(typeof(ICollection<WcoSnippetCloneData>))]
	[KnownType(typeof(ICollection<WCOSnippetData>))]
	[KnownType(typeof(ICollection<WcoSnippetDetachment>))]
	[KnownType(typeof(ICollection<WcoVariantAddition>))]
	[KnownType(typeof(ICollection<WcoVariantChangeset>))]
	[KnownType(typeof(ICollection<WcoVariantDeletion>))]
	[KnownType(typeof(ICollection<WorkflowCommandData>))]
	[KnownType(typeof(ICollection<WorkflowListItem>))]
	[KnownType(typeof(ICollection<WorkflowScheduleItem>))]
	[KnownType(typeof(ICollection<WorkflowStepCommandsData>))]
	[KnownType(typeof(ICollection<WorklistAsset>))]
	[KnownType(typeof(ICollection<WorklistAssetAndFields>))]
	[KnownType(typeof(ICollection<WorklistPreferenceData>))]
	[KnownType(typeof(ICollection<Guid>))]
	[KnownType(typeof(ICollection<int>))]
	[KnownType(typeof(ICollection<string>))]
	[KnownType(typeof(KeyValuePair<int, ActionData>))]
	[KnownType(typeof(KeyValuePair<string, CancelUploadResponse>))]
	[KnownType(typeof(KeyValuePair<string, string>))]
	[KnownType(typeof(DayOfWeek))]
	public class FilterExpression : INotifyPropertyChanged
	{
		private bool CheckListsField;

		private CrownPeak.AccessAPI.Comparison ComparisonField;

		private string FieldNameField;

		private CrownPeak.AccessAPI.JoinType JoinTypeField;

		private AssetPropertyNames PropertyNameField;

		private object ToCompareField;

		private string UIParamsField;

		[DataMember]
		public bool CheckLists
		{
			get
			{
				return this.CheckListsField;
			}
			set
			{
				if (!this.CheckListsField.Equals(value))
				{
					this.CheckListsField = value;
					this.RaisePropertyChanged("CheckLists");
				}
			}
		}

		[DataMember]
		public CrownPeak.AccessAPI.Comparison Comparison
		{
			get
			{
				return this.ComparisonField;
			}
			set
			{
				if (!this.ComparisonField.Equals(value))
				{
					this.ComparisonField = value;
					this.RaisePropertyChanged("Comparison");
				}
			}
		}

		[DataMember]
		public string FieldName
		{
			get
			{
				return this.FieldNameField;
			}
			set
			{
				if (!object.ReferenceEquals(this.FieldNameField, value))
				{
					this.FieldNameField = value;
					this.RaisePropertyChanged("FieldName");
				}
			}
		}

		[DataMember]
		public CrownPeak.AccessAPI.JoinType JoinType
		{
			get
			{
				return this.JoinTypeField;
			}
			set
			{
				if (!this.JoinTypeField.Equals(value))
				{
					this.JoinTypeField = value;
					this.RaisePropertyChanged("JoinType");
				}
			}
		}

		[DataMember]
		public AssetPropertyNames PropertyName
		{
			get
			{
				return this.PropertyNameField;
			}
			set
			{
				if (!this.PropertyNameField.Equals(value))
				{
					this.PropertyNameField = value;
					this.RaisePropertyChanged("PropertyName");
				}
			}
		}

		[DataMember]
		public object ToCompare
		{
			get
			{
				return this.ToCompareField;
			}
			set
			{
				if (!object.ReferenceEquals(this.ToCompareField, value))
				{
					this.ToCompareField = value;
					this.RaisePropertyChanged("ToCompare");
				}
			}
		}

		[DataMember]
		public string UIParams
		{
			get
			{
				return this.UIParamsField;
			}
			set
			{
				if (!object.ReferenceEquals(this.UIParamsField, value))
				{
					this.UIParamsField = value;
					this.RaisePropertyChanged("UIParams");
				}
			}
		}

		public FilterExpression()
		{
		}

		protected void RaisePropertyChanged(string propertyName)
		{
			PropertyChangedEventHandler propertyChangedEventHandler = this.PropertyChanged;
			if (propertyChangedEventHandler != null)
			{
				propertyChangedEventHandler(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public event PropertyChangedEventHandler PropertyChanged;
	}
}